version: '3'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  update-nix-hash:
    desc: Automatically update the vendorHash in flake.nix after Go dependency changes
    cmds:
      - go run bin/update-nix-hash.go

  build:
    desc: Build the project with Nix
    cmds:
      - nix build

  dev:
    desc: Enter the Nix development shell
    cmds:
      - nix develop

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf result result-*

  fmt:
    desc: Format nix files
    cmds:
      - nix fmt

  check:
    desc: Check flake syntax and run checks
    cmds:
      - nix flake check
