version: '3'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  nix-update-hash:
    desc: Automatically update the vendorHash in flake.nix after Go dependency changes
    cmds:
      - go run scripts/update-nix-hash.go

  nix-build:
    desc: Build the project with Nix
    cmds:
      - nix build

  nix-dev:
    desc: Enter the Nix development shell
    cmds:
      - nix develop

  nix-fmt:
    desc: Format nix files
    cmds:
      - nix fmt

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf result result-*

  nix-check:
    desc: Check flake syntax and run checks
    cmds:
      - nix flake check
