name: "nix-update-hash"

on:
  push:
    paths:
      - 'go.mod'
      - 'go.sum'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-hash:
    uses: datum-cloud/actions/.github/workflows/nix-update-hash.yaml@main
    secrets: inherit
