name: "nix-update-hash"

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'go.mod'
      - 'go.sum'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-hash:
    uses: datum-cloud/actions/.github/workflows/nix-update-hash.yaml@v1.22.0
    secrets: inherit
