name: "update-notice"

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'go.mod'
      - 'go.sum'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-notice:
    uses: datum-cloud/actions/.github/workflows/update-notice.yaml@v1.22.0
    secrets: inherit
